server:
    port: 8080
spring:
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html

    datasource:
        url: jdbc:mysql://localhost:3306/testformvc?serverTimezone=UTC&useSSL=false
        username: root
        password: a057992563
        driver-class-name: com.mysql.cj.jdbc.Driver

    http:
        encoding:
            force: true

